### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by baizon** [martinbaillie/packer-plugin-ami-copy#105]
Hi, could You please merger the dependabot PR and make a new release. Security updates and stuff. Thanks

**Comment by martinbaillie** [comment]
Done: https://github.com/martinbaillie/packer-plugin-ami-copy/releases/tag/v1.9.0

**Comment by baizon** [comment]
The new release is missing the linux release. Could you fix that? The release pipeline is working again, so that should also make a linux release. Thanks.

**Comment by baizon** [comment]
The latest 1.9.0 release files are missing the file extension (.zip). Could You please fix that, thanks.
