### ISSUE TITLE
Release v1.9.0 missing file extensions

### ISSUE THREAD

**Issue by baizon** [martinbaillie/packer-plugin-ami-copy#107]
Hi, the latest [v1.9.0 release](https://github.com/martinbaillie/packer-plugin-ami-copy/releases/tag/v1.9.0) is missing the file extensions. It seems that You have created this release manually. I would recommend to create a v1.9.1 release with the pipeline.
Edit: Or is this a new build procedure and binaries are deployed? If yes, then why the change? I'm asking, because our pipeline is working with .zip and we would have to change the logic.

**Comment by baizon** [comment]
Also there seems to be checksum fail:
```
 ERROR: Checksum on GitHub: ebba6040652d7a118d46f698ac1d8bbea67ff7fabe28d856a9947c7ccf2f7507
2.492 5d667c1dbf11157e7cbfcb9e413ec5a2a5bdcd69dc8a2ccd1fc5fba71e25e86a, Checksum download: ebba6040652d7a118d46f698ac1d8bbea67ff7fabe28d856a9947c7ccf2f7507
```

**Comment by martinbaillie** [comment]
I had copied it across from another one of my old projects. I've switched it back now and got it working again. Hopefully this release has what you need in the layout you need it: https://github.com/martinbaillie/packer-plugin-ami-copy/releases/tag/v1.9.3
