### ISSUE TITLE
filename is not correct in v1.9.4 for linux amd64 

### ISSUE THREAD

**Issue by hche608** [martinbaillie/packer-plugin-ami-copy#115]
[packer-plugin-ami-copy_v1.9.4_x5.0_linux_amd64.zip](https://github.com/martinbaillie/packer-plugin-ami-copy/releases/download/v1.9.4/packer-plugin-ami-copy_v1.9.4_x5.0_linux_amd64.zip)

this does not contain correct filename
actual: packer-plugin-ami-copy
expect: packer-plugin-ami-copy_v1.9.3_x5.0_linux_amd64

**Comment by dmonagha** [comment]
Issue exists in ``v1.9.3`` as well

**Comment by martinbaillie** [comment]
Fixed in v1.9.5, thanks @vinaysaraogiloopio
