### ISSUE TITLE
Protocol issue with Packer 1.7

### ISSUE THREAD

**Issue by SJM-J2** [martinbaillie/packer-plugin-ami-copy#14]
Getting the following when using the plugin w/ Packer 1.7

`error initializing post-processor 'ami-copy': The protocol of this plugin
(protocol version 4 and lower) was deprecated, please use a newer version of
this plugin.Or use an older version of Packer (pre 1.7) with this plugin.`

**Comment by vishalbasra** [comment]
yes, on packer 1.7 w packer init only multi-component plugins are allowed, I similarly raised https://github.com/martinbaillie/packer-post-processor-ami-copy/issues/13 and https://discuss.hashicorp.com/t/plugin-nomenclature-change/21887/6 which basically led me to https://packer-git-master-hashicorp.vercel.app/docs/plugins#installing-plugins 
for now using this plugin is more important to me than using HCL2 or packer 1.7 so I'm using packer 1.6.6

**Comment by martinbaillie** [comment]
Please give https://github.com/martinbaillie/packer-plugin-ami-copy/releases/tag/v1.7.0 a shot. I've refactored the project to align to Hashicorp's latest plugin architecture but I don't use this anymore so can't easily test myself.

**Comment by SJM-J2** [comment]
@martinbaillie you rock. I'll carve out some time to test this out next week and let you know. much appreciated, seriously

**Comment by SJM-J2** [comment]
@martinbaillie sorry for the delay, but can confirm the new version works with 1.7. Thanks again
