### ISSUE TITLE
The docs/ and examples/ link in the Readme return 404

### ISSUE THREAD

**Issue by shrutis31** [martinbaillie/packer-plugin-ami-copy#37]
Hi,
The docs/ and examples/ link here https://github.com/martinbaillie/packer-plugin-ami-copy#usage return a 404 error code. Can you fix this please!

**Comment by mattgialelis** [comment]
Would also be great to get an idea of what parameters are supported and can be used, along with any IAM perms required to use this.

**Comment by evandena** [comment]
> Hi, The docs/ and examples/ link here https://github.com/martinbaillie/packer-plugin-ami-copy#usage return a 404 error code. Can you fix this please!

https://github.com/martinbaillie/packer-plugin-ami-copy/tree/master/example works for examples
